---
title: "MSI through time"
author: "Benjamin Uveges"
date: '2022-10-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

list_of_packages = c("plotly","htmlwidgets","tidyverse", "MetBrewer","stringr", "readxl")

lapply(list_of_packages, 
       function(x) if(!require(x,character.only = TRUE)) install.packages(x))

# Configuring database #### 
coltypes <- c("text","text","text","text","text","text","text","numeric","numeric","numeric",
              "text","text","text","text","text","text","text","numeric","numeric","numeric",
              "numeric","numeric","numeric","numeric","text","text","text","text","numeric")
df <- read_excel("New_MIF_database.xlsx", col_types = coltypes)

# Setting phase factor levels and adding a simplified analysis type, spot/bulk
df <- df %>% 
  mutate(Phase = factor(Phase, 
                        levels = c("Sulfide", "Sulfate","Total S","Sulfide + Organic S", "Organic S")),
         Spot.Bulk = if_else(Analysis.Type %in% c("SIMS", "KrF Spot Fluorination, SF6","In-situ Laser","SHRIMP-SI",
                                                  "CO2 Spot Laser FLuorination, SF6","LA-MC-ICP-MS (spot)"),"Spot","Bulk"))

# Adding calculated columns of d33 and d36
df <- df %>% mutate(d33s = (D33S + 1000*(((1+(d34s/1000))^0.515)-1)),
                    d36s = (D36S + 1000*(((1+(d34s/1000))^1.90)-1)))

# Adding time bin column. Bin size = cutW in millions of years.
cutW <- 50  # Time bin size

df <- df %>% 
  mutate(group =cut_width(age.mean,cutW,closed="left"))
df <- df %>% mutate(group.age  = parse_number(as.character(strsplit(as.character(df$group), ",")))+(cutW/2))

# Finding data that conform to specific simpliefied lithologies
carb <- grep("limestone|carbonate|dolomite|dolostone|wacke|marble",df$Lithology, ignore.case = TRUE)
hsil <- grep("sand|quartzite|coarse|conglomerate|arenite|aenite|quartz",df$Lithology, ignore.case = TRUE)
lsil <- grep("shale|silt|silstone|mud|phyllit|argillite|schist|marl|pelite",df$Lithology, ignore.case = TRUE)
sulf <- grep("sulfate|evapo|barite|gypsum|anhydrite",df$Lithology, ignore.case = TRUE)
chem <- grep("chert|iron|jasper|BIF|chemical|fe-oxyde|Sed BC|massive sulfide|macro|microscopic sulfide",df$Lithology, ignore.case = TRUE)
microb <- grep("stromat|microb",df$Lithology, ignore.case = TRUE)
alt <- grep("vein|ore body|hydrothermal|colloform|alteration|matatonalite",df$Lithology, ignore.case = TRUE)
glac<- grep("glacial|diamictite|tillite|dropstone|gravity",df$Lithology, ignore.case = TRUE)
ign <- grep("gabbro|basalt|intrusion|volcan|dyke|gneiss|ash|spherule|komati|mafic|dolerite|tuff|hornblende|pyroxene|lava|dacite|amphybollite",df$Lithology, ignore.case = TRUE)
igsed <- grep("ash|tuff|volcanoclastic|silicified volcanic|volcanic sandstone|felsic volcanics",df$Lithology, ignore.case = TRUE)
detr <- grep("detrital",df$Mineralogy, ignore.case = TRUE)
bif <- grep("iron|jasper|BIF",df$Lithology, ignore.case = TRUE)
df <- df %>% mutate(simp.lith = NA)

# Assigning simplified lithologies based on above, in new column, Simp.Lith
df$simp.lith[carb] <- "Carbonates"
df$simp.lith[hsil] <- "High Energy Siliciclastic"
df$simp.lith[sulf] <- "Sulfates"
df$simp.lith[chem] <- "Chemical"
df$simp.lith[lsil] <- "Low Energy Siliciclastic"
df$simp.lith[microb] <- "Microbial"
df$simp.lith[alt] <- "Altered/Late Addition"
df$simp.lith[glac] <- "Glacial/Diamictite/Detrital"
df$simp.lith[ign] <- "Igneous"
df$simp.lith[igsed] <- "Volcanic Sed"
df$simp.lith[is.na(df$simp.lith)] <- "None Provided"
df$simp.lith[detr] <- "Glacial/Diamictite/Detrital"

# Ordering simplified lithology factor levels
df <- df %>% mutate(simp.lith = factor(simp.lith, levels = c("High Energy Siliciclastic",
                                                             "Low Energy Siliciclastic","Carbonates",
                                                             "Sulfates","Chemical","Microbial",
                                                             "Altered/Late Addition",
                                                             "Glacial/Diamictite/Detrital","Igneous","Volcanic Sed","None Provided")))
# Adding 'Era' column, and setting factor level order
df <- df %>% mutate(Era = if_else(age.mean>= 3600, 'Eoarchean',
                                  if_else(age.mean>= 3200, 'Paleoarchean',
                                          if_else(age.mean>= 2800, 'Mesoarchean',
                                                  if_else(age.mean>= 2500, 'Neoarchean',
                                                          if_else(age.mean>= 1600, 'Paleoproterozoic', 'Mesoproterozoic-Present')))))) %>% 
  mutate(Era = factor(Era, levels =c('Eoarchean','Paleoarchean','Mesoarchean','Neoarchean','Paleoproterozoic', 'Mesoproterozoic-Present') )) %>% 
  mutate(Phase2 = if_else(Phase == "Sulfide"&Spot.Bulk== "Bulk", "Sulfide Bulk", 
                          if_else(Phase == "Sulfide"&Spot.Bulk== "Spot", "Sulfide Spot",
                                  if_else(Phase == "Sulfate"&Spot.Bulk== "Bulk", "Sulfate Bulk",
                                          if_else(Phase == "Sulfate"&Spot.Bulk== "Spot", "Sulfate Spot", as.character(Phase)))))) %>% 
  mutate(Phase2=factor(Phase2, 
                       levels = c("Sulfide Bulk", "Sulfide Spot", "Sulfate Bulk","Sulfate Spot",
                                           "Total S", "Sulfide + Organic S", "Organic S")))

df <- df %>% drop_na(D33S)

# Gathering sulfur data to one column (dropping sig values), and setting factor levels
dfgat <- select(df,-c(sig.d34s,sig.D33S,sig.D36S)) %>% 
  gather(key = "name", value = "value",c(d34s,D33S,D36S)) %>% 
  mutate(name = factor(name, levels = c("d34s","D33S","D36S")))

# Setting palette
pal <- MetBrewer::met.brewer(name = "Hokusai1",7)
pal <- c(pal[7:1])

```

## Multiple Sulfur Isotope Record Through Time

```{r D33STime, echo=FALSE, warning=FALSE, out.width='90%'}
# ∆33S through time plot ####

D33Stest <- plot_ly(data = df,  # setting data
                 colors = pal, # setting colors
                 x =~age.mean, 
                 y =~D33S, 
                 color =~Phase2, 
                 #symbol = ~Spot.Bulk,symbols = c('circle','diamond'),  # setting aesthetics(mapping)
                 #legendgroup= "SulfideBulk",
                 showlegend=TRUE,
                 visible = TRUE,
                 text= ~paste("Type: ",Phase,"<br>Age (Myr): ", age.mean, # setting text for hover display
                              "<br>Craton: ", Craton,
                              "<br>Supergroup: ",Supergroup,
                              "<br>Group: ", Group, 
                              "<br>Subgroup: ", Subgroup,
                              "<br>Formation: ", Formation, 
                              "<br>Member: ", Member,
                              "<br>Core: ", Core,
                              "<br>Lithology: ", Lithology,
                              "<br>Mineralogy: ", Mineralogy,
                              "<br>Analysis Type: ", Analysis.Type,
                              "<br>∆<sup>33</sup>S (‰): ", round(D33S,digits=2), "<br>Source: ", Source),
                 hoverinfo = 'text', 
                 customdata = paste0("https://scholar.google.com//scholar?hl=en&as_sdt=0%2C22&q=", df$DOI),
                 type = 'scatter', mode = 'markers') %>%   # manually setting type to scatter point figure
  # name = "δ<sup>34</sup>S (‰)") %>%  # setting name for legend
  layout(yaxis = list(title='∆<sup>33</sup>S (‰)', hoverformat =  '.2f'),
         legend = list(categoryorder = list("Sulfide Bulk", "Sulfide Spot", "Sulfate Bulk","Sulfate Spot",
                                     "Total S Bulk", "Sulfide + Organic S Bulk", "Organic S Spot"))
  )


D33Stest <- D33Stest %>% layout(
  title = "∆<sup>33</sup>S (‰) Through Time",
  legend=list(title=list(text='<b>Sulfur Phase and <br>Analysis Type' )),
  yaxis = list(title='∆<sup>33</sup>S (‰)', hoverformat =  '.2f'), # Setting y axis name
  xaxis = list(title = "Age (Myr)",
               autorange="reversed"),
  font = list(size = 10),
  annotations = 
    list(x = 0.9, y = 0, text = "Uveges et al., 2022", 
         showarrow = F, xref='paper', yref='paper', 
         xanchor='right', yanchor='auto', xshift=0, yshift=0,
         font=list(size=15, color="grey")),
  margin = list(b = 100, l = 50, t = 50))# %>% 
 # add_markers(customdata = paste0("https://scholar.google.com//scholar?hl=en&as_sdt=0%2C22&q=", df$DOI),
                                  #  showlegend=FALSE, visible = FALSE)

p2 <- onRender(
  D33Stest, "
  function(el) {
    el.on('plotly_click', function(d) {
      var url = d.points[0].customdata;
      window.open(url);
    });
  }
")

#p <- htmlwidgets::saveWidget(partial_bundle(as_widget(p2)), "Cap33S_time_fig2.html")
p2

```
